### ISSUE TITLE
GEAR modes and power consumption 

### ISSUE THREAD

**Issue by xains** [mill1000/midea-ac-py#161]
So I would request you to add the missing GEAR modes which are available as a button on the RC. 75 and 50. 

Secondly, the power consumption is all over the place, not providing correct data. 

Please ask me for anything you would like me to provide. 

Grateful to you guys. Absolutely. 

Cheers!

**Comment by dean-dalianis** [comment]
Since my Carrier AC units also don't provide power consumption data, I found a workaround by creating a custom sensor. This sensor estimates power consumption based on the AC model (consumption specifications), the operating mode, the current and target temperatures, and the duration of operation. I must clarify that I am not entirely confident in the accuracy of this method.

Would it be possible to include a similar feature?

Cheers!

**Comment by mill1000** [comment]
> Since my Carrier AC units also don't provide power consumption data, I found a workaround by creating a custom sensor. This sensor estimates power consumption based on the AC model (consumption specifications), the operating mode, the current and target temperatures, and the duration of operation. I must clarify that I am not entirely confident in the accuracy of this method.

That's clever. The accuracy is probably most limited by not knowing when its actively cooling/heating. Unfortunately the device doesn't provide that information.

> Would it be possible to include a similar feature?
> 
> Cheers!

I think this would be out of scope for the integration.

**Comment by mill1000** [comment]
Closing as a duplicate since Gear support has already been requested.
