### ISSUE TITLE
configuration failed 

### ISSUE THREAD

**Issue by VillaFlamingo** [mill1000/midea-ac-py#215]
Good morning, I recently integrated my Ferroli air conditioners, but I continue to have configuration errors. to make them operational again I have to delete them and reinsert them. However, I have noticed that even in the application I sometimes have to refresh to get them to connect. what could it depend on? I attach the error log.
[home-assistant_midea_ac_2024-08-19T08-41-15.534Z.log](https://github.com/user-attachments/files/16657935/home-assistant_midea_ac_2024-08-19T08-41-15.534Z.log)

**Comment by mill1000** [comment]
Hi.

Based on your logs you may be having some general network issues. Your Shelly devices were also reporting errors. This would also explain why the OEM app also has issues.

Otherwise your devices appears to be working fine, except for 192.168.1.102 which was causing most of the errors. Try setting the Maximum Connection Lifetime to 90 seconds for this device.

**Comment by mill1000** [comment]
Closing as stale.
