### ISSUE TITLE
Request investigation into supporting tower fan FZ10-21CR

### ISSUE THREAD

**Issue by katelovescode** [mill1000/midea-ac-py#272]
I bought a Midea FZ10-21CR Oscillating Tower Fan from Amazon a few weeks ago, and it's configured via the SmartHome app from Midea.  Is there any way to investigate if it's supported?  I'm not a python dev, but I've been picking through the codebase and I know the Midea API is challenging at best, so I'm not really sure where to start to try and make a new PR myself.  Hence the request!  Thanks. 😄

**Comment by mill1000** [comment]
Hi,

You may find your device is already supported by this integration: https://github.com/wuwentao/midea_ac_lan

Otherwise supporting a new device type first requires implementing support in the underlying library here: https://github.com/mill1000/midea-msmart

The first step in supporting another device type is downloading the protocol. These existing issues may be of help:
https://github.com/mill1000/midea-msmart/issues/107
https://github.com/mill1000/midea-msmart/issues/100
https://github.com/mill1000/midea-msmart/issues/110

**Comment by katelovescode** [comment]
Thanks @mill1000 - I'll take a look and see if it works, and if not maybe I can try to open some PRs on that midea-msmart library.  Thank you!

**Comment by katelovescode** [comment]
Just wanted to follow up - the reason I initially had abandoned that library is because the HACS version is pointing to the old repository, which doesn't download anymore, but when I manually installed and configured, it did in fact find my fan.  Thanks for pointing me in this direction!
