### ISSUE TITLE
Fan Speed Issues

### ISSUE THREAD

**Issue by LexanRed** [mill1000/midea-ac-py#96]
Hello, 

thanks for your work and this awesome integration! 

Unfortunately I ran into some problems with the fan control. 

1. Whenever the AC is turned off, the fan control is unavailable
<img width="491" alt="Screenshot 2024-02-22 at 11 16 53" src="https://github.com/mill1000/midea-ac-py/assets/57357219/4bddc41c-bec1-4d5c-8f66-297fff673fe8">

2. When the fan is set on auto, the range can exceed 100%
<img width="486" alt="Screenshot 2024-02-22 at 11 17 07" src="https://github.com/mill1000/midea-ac-py/assets/57357219/37fbc482-01af-480b-a7e1-df09c97b6736">

3. The option "Custom" is only available, when the slider was set manually
<img width="571" alt="Screenshot 2024-02-22 at 11 19 26" src="https://github.com/mill1000/midea-ac-py/assets/57357219/de165c82-70f8-4495-9647-8e0e53533f78">
<img width="149" alt="Screenshot 2024-02-22 at 11 19 10" src="https://github.com/mill1000/midea-ac-py/assets/57357219/4cbd88c3-6628-44dc-a45c-940b5140d08b">

4. (Not a bug) I think it would be nicer, if there was nothing selected in the fan speed dropdown, when the slider was set manually instead of adding the "custom" option which then disappears again when selecting something from the dropdown.
<img width="585" alt="Screenshot 2024-02-22 at 11 19 02" src="https://github.com/mill1000/midea-ac-py/assets/57357219/8ed37904-97c7-4c67-9e57-b692675d2553">

5. There is no way to set the speed to full power from the dropdown. High is only 80%. 

Thanks for any feedback. 

Alex

**Comment by mill1000** [comment]
Thanks for the input and thanks for using the integration.

Some of these points are not new and I'll try to explain the why of them.

---
> 1. Whenever the AC is turned off, the fan control is unavailable

This is expected behavior. If a device is off, it is not possible to control the fan speed. 

The only means to disable a control in HA is to mark it as unavailable (as far as I know). So it seemed reasonable to do so. This approach also seems inline with HA's description of the `available` property.
> https://developers.home-assistant.io/docs/core/entity/#registry-properties
>> | Name | Type | Default | Description |
>> | -- | -- | -- | -- |
>> | available | bool | True | Indicate if Home Assistant is able to read the state and control the underlying device. |

----
> 2. When the fan is set on auto, the range can exceed 100%

Also expected, but confusing. (Reported in #72 too). 

In short, the device encodes "auto" as a value of 102, but I can't (to my knowledge) get the actual fan speed. So I can either display the value as is (current behavior), or limit it's value to 100 in the number entity. However I felt this would be misrepresenting the setting.

I'm open to ideas on how to make this cleaner.

---
> 3. The option "Custom" is only available, when the slider was set manually
> 4. (Not a bug) I think it would be nicer, if there was nothing selected in the fan speed dropdown, when the slider was set manually instead of adding the "custom" option which then disappears again when selecting something from the dropdown.

This was on purpose as I wanted to indicate to the user that a "custom" fan speed had been set via the slider. However, I am interested in your suggestion of setting the selector to blank so I will experiment with that.

> 5. There is no way to set the speed to full power from the dropdown. High is only 80%.

Yes that is correct. Some users reported issues when I tried to use 100% as "high" (#67, https://github.com/mill1000/midea-msmart/issues/95). It seems the official value for "high" is 80%.

I could add an additional speed (max? full?) when the device supports custom speeds to set it to 100%.

**Comment by v1k70rk4** [comment]
I think the appearance is perfect like this:
102 is the AUTO
101 is the dehumidification
if you want it really nice, it could be that if it's over 100 then it greys out, but it's perfect as it is.

**Comment by mill1000** [comment]
Thanks, I appreciate the additional input.

**Comment by mill1000** [comment]
The latest release includes an additional "Max" fan speed when the device supports custom fan speeds.
